def main():

    display_intro()
    main_menu()

def display_intro():
    """
    Prints the introductory message in the terminal.

    ASCII text art generated by: https://fsymbols.com/generators/carty/
    """
    print('░██████╗██╗░░░██╗██████╗░░█████╗░██╗░░██╗██╗░░░██╗')
    print('██╔════╝██║░░░██║██╔══██╗██╔══██╗██║░██╔╝██║░░░██║')
    print('╚█████╗░██║░░░██║██║░░██║██║░░██║█████═╝░██║░░░██║')
    print('░╚═══██╗██║░░░██║██║░░██║██║░░██║██╔═██╗░██║░░░██║')
    print('██████╔╝╚██████╔╝██████╔╝╚█████╔╝██║░╚██╗╚██████╔╝')
    print('╚═════╝░░╚═════╝░╚═════╝░░╚════╝░╚═╝░░╚═╝░╚═════╝░')
    print('\n')
    print('█▄▄ █▄█ ▀   █▀ █░█ ▄▀█ █▄░█ █▀▀   █▀▀ █▀█ █▀█ █▄▀')
    print('█▄█ ░█░ ▄   ▄█ █▀█ █▀█ █░▀█ ██▄   █▄▄ █▄█ █▄█ █░█')
    print('\n')

def main_menu():
    display_menu()

def display_menu():
    """
    Prints the main menu options in the terminal.

    ASCII text art generated by: https://fsymbols.com/generators/carty/
    """  
    print('█▀▄▀█ ▄▀█ █ █▄░█   █▀▄▀█ █▀▀ █▄░█ █░█')
    print('█░▀░█ █▀█ █ █░▀█   █░▀░█ ██▄ █░▀█ █▄█\n')
    print('(1) New Game')
    print('(2) Load Game')
    print('(3) How to Play')
    print('(4) Quit\n')
    

if __name__ == '__main__':
    main()